version: "3.9"

services: 
  database:  
    image: postgres
    container_name: taskflow-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes: 
      - taskflow-db-data:/var/lib/postgresql
    networks:
      - taskflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 5s
    
  api: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskflow-api 
    env_file:
      - .env
    environment: 
      - DATABASE_URL=${DATABASE_URL}
    ports: 
      - "8080:8080"
    networks:
      - taskflow-network
    depends_on: 
      database:
        condition: service_healthy
    restart: unless-stopped

volumes: 
  taskflow-db-data:

networks:
  taskflow-network: